### ISSUE TITLE
Compatibility issues with Laravel 8 + Livewire 2 + Tailwind 2

### ISSUE THREAD

**Issue by Triumfator-M** [Light-it-labs/laravel-livewire-cart#14]
This is a very promising livewire cart package, but I have problems running it with Laravel 8.27 + Livewire 2 + Tailwind 2.0.3 and WITHOUT turbolinks since Livewire 2.0 dropped it.

Steps I used trying to get it to work....
$updatesQueryString changed to $queryString
There was only one instance.

Modified \App\Http\Livewire\Products.php file as follows. Product search / pagination / display work. I just cannot get product added to cart.

```php
public function mount(): void
    {
        // Livewire 2 - no longer necessary.
        // $this->search = request()->query('search', $this->search);        
    }
```
Livewire 2 routing was changed as per their recommendations. Home and products routes work perfectly.

```php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\Home;
use App\Http\Livewire\Cart;
use App\Http\Livewire\Products;

Route::get('/', Home::class)->name('home');
Route::get('/cart', Cart::class)->name('cart');
Route::get('/products', Products::class)->name('products');
```

When i try adding product to cart , here's the eror i get.

**Illuminate\Contracts\Container\BindingResolutionException**
**Target class [cart] does not exist.**

This is the \app\Facades\Cart.php file

```php
<?php

namespace App\Facades;

use Illuminate\Support\Facades\Facade;

class Cart extends Facade
{
    public static function getFacadeAccessor()
    {
       return 'cart';
    }
}
```

This is the \App\Helpers\Cart.php file

```php
<?php

namespace App\Helpers;

use App\Models\Product;

class Cart
{
    public function __construct()
    {
        if($this->get() === null)
            $this->set($this->empty());
    }

    public function add(Product $product): void
    {
        $cart = $this->get();
        array_push($cart['products'], $product);
        $this->set($cart);
    }

    public function remove(int $productId): void
    {
        $cart = $this->get();
        array_splice($cart['products'], array_search($productId, array_column($cart['products'], 'id')), 1);
        $this->set($cart);
    }

    public function clear(): void
    {
        $this->set($this->empty());
    }

    public function empty(): array
    {
        return [
            'products' => [],
        ];
    }

    public function get(): ?array
    {
        return request()->session()->get('cart');
    }

    private function set($cart): void
    {
        request()->session()->put('cart', $cart);
    }
}
```

**Comment by Triumfator-M** [comment]
Actually I got this resolved....
If anyone is having a similar issue, this is because config/app.php configuration file was missing 2 lines...

This might be helpful to anyone who wants to use this package with laravel 8 / tailwind 2 / livewire 2.

**Comment by pedrobaratafernandes** [comment]
i have the same problem can you share the code?

for the problem:
**Illuminate\Contracts\Container\BindingResolutionException
Target class [cart] does not exist.**

i change the return

```php
<?php


namespace App\Facades;


use Illuminate\Support\Facades\Facade;


class Cart extends Facade
{
    public static function getFacadeAccessor()
    {
        return '\App\Helpers\Cart';
    }
}

```

**Comment by Triumfator-M** [comment]
Please read my post about how I fixed this problem. I don't have the code
anymore.

Best regards,
Vlad

**Comment by josegus** [comment]
did this project even work?

the property $cart is not one of the supported Livewire types
