### ISSUE TITLE
paginate error?

### ISSUE THREAD

**Issue by ddammo55** [Light-it-labs/laravel-livewire-cart#2]
Thank you first.

Error after clicking the page button after searching

https://livewire-shopping-cart.demo.lightit.io/livewire/message/products?page=4

Oops! An Error Occurred
The server returned a "405 Method Not Allowed".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by JuanNitram** [comment]
Hello! Thank you for communicating this issue. We just corrected it in the last commit that we made.
