### ISSUE TITLE
Returning a notification package in after Adding to cart

### ISSUE THREAD

**Issue by oluwatosinolamilekan** [Light-it-labs/laravel-livewire-cart#3]
![image](https://user-images.githubusercontent.com/29930457/83092814-06551800-a096-11ea-85ce-abb06bcd320e.png)

**Comment by oluwatosinolamilekan** [comment]
that an example of redirecting the redirecting a message for fake login but guess it not working..

**Comment by JuanNitram** [comment]
Good! The example does not cover those functionalities. Anyway, I leave you a link to the documentation that may be useful!

[Laravel-Livewire-Redirecting](https://laravel-livewire.com/docs/redirecting)
